# Generated by Django 4.2.9 on 2024-01-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userprofile_skills_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
